$(document).ready(function(){
  $(".first").click(function(){
    $("#java").fadeToggle(1000)
  });
  $(".left").click(function(){
    $("#def").fadeToggle(1000)
  });
  $(".right").click(function(){
    $("#pri").fadeToggle(1000)
  });
  $(".num").click(function(){
    $("#numdef").fadeToggle(1000)
  });
  $(".string").click(function(){
    $("#stridef").fadeToggle(1000)
  });
  $(".boo").click(function(){
    $("#boodef").fadeToggle(1000)
  });
  $(".null").click(function(){
    $("#nulldef").fadeToggle(1000)
  });
  $(".und").click(function(){
    $("#unddef").fadeToggle(1000)
  });
  $(".sym").click(function(){
    $("#symdef").fadeToggle(1000)
  });
})